///List of all things that can be dispensed by an arcade cabinet and the weight of them being picked.
GLOBAL_LIST_INIT(arcade_prize_pool, list(
	/obj/item/toy/gun = 2,
	/obj/item/storage/crayons = 2,
	/obj/item/toy/cards/deck = 2,
	/obj/item/clothing/glasses/regular = 2,
	/obj/item/toy/redbutton = 2,
	/obj/item/toy/talking/owl = 2,
	/obj/item/toy/talking/griffin = 2,
	/obj/item/restraints/handcuffs/fake = 2,
	/obj/item/toy/eightball = 2,
	/obj/item/extendohand/acme = 1,
	/obj/item/hot_potato/harmless/toy = 1,
	/obj/item/toy/plush/shark = 2,
	/obj/item/toy/brokenradio = 2,
	/obj/item/toy/foamfinger = 2,
	/obj/item/clothing/glasses/trickblindfold = 2,
	/obj/item/stack/spacecash/c1 = 12,
	/obj/item/food/pierogi_ration = 1,
	/obj/item/reagent_containers/cup/soda_cans/breenwater = 2,
	/obj/item/reagent_containers/cup/soda_cans/breenwater/yellow = 4,
	/obj/item/reagent_containers/cup/soda_cans/breenwater/purple = 1,
	/obj/item/reagent_containers/cup/soda_cans/breenwater/red = 1,
	/obj/item/food/nutripaste = 1,
))
