#define NO_FACTION 0
#define COMBINE_DEPLOYMENT_FACTION 1
#define REBEL_DEPLOYMENT_FACTION 2

#define DEPLOYMENT_TIER1_REBELS 0
#define DEPLOYMENT_TIER2_REBELS 50
#define DEPLOYMENT_TIER3_REBELS 100
#define DEPLOYMENT_TIER4_REBELS 275

#define DEPLOYMENT_TIER1_COMBINE 0
#define DEPLOYMENT_TIER2_COMBINE 50
#define DEPLOYMENT_TIER3_COMBINE 125
#define DEPLOYMENT_TIER4_COMBINE 300
