export type AvailableJob = keyof typeof JOB2ICON;

/** Icon map of jobs to their fontawesome5 (free) counterpart. */
export const JOB2ICON = {
  Dispatch: 'eye',
  Citizen: 'person-walking-luggage',
  'Infestation Control': 'bug-slash',
  Bartender: 'cocktail',
  'Bit Avatar': 'code',
  Bitrunner: 'gamepad',
  Botanist: 'seedling',
  'Bridge Assistant': 'building-shield',
  'District Administrator': 'crown',
  'Cargo Gorilla': 'paw',
  'Union Worker': 'box',
  'CentCom Commander': 'star',
  'CentCom Head Intern': 'pen-fancy',
  'CentCom Intern': 'pen-alt',
  'CentCom Official': 'medal',
  Chaplain: 'cross',
  Chef: 'utensils',
  Chemist: 'prescription-bottle',
  'Chief Engineer': 'user-astronaut',
  'Chief Medical Officer': 'user-md',
  Clown: 'face-grin-tears',
  Cook: 'utensils',
  Coroner: 'skull',
  Curator: 'dollar-sign',
  Clerk: 'dollar-sign',
  'Cyber Police': 'qrcode',
  Cyborg: 'robot',
  Conscript: 'shield-halved',
  Geneticist: 'dna',
  'Labor Lead': 'briefcase',
  'Overwatch Soldier': 'user-shield',
  'Big Brother': 'eye',
  'Vortigaunt Slave': 'hands-bound',
  'District Liaison': 'user-tie',
  'Union Doctor': 'staff-snake',
  Mime: 'comment-slash',
  Paramedic: 'truck-medical',
  'Personal AI': 'mobile-alt',
  Rebel: 'tree',
  Psychologist: 'brain',
  'Union Foreman': 'sack-dollar',
  'Research Director': 'user-graduate',
  Roboticist: 'battery-half',
  'Union Scientist': 'flask',
  'Civil Protection Officer (Cargo)': 'shield-halved',
  'Engineering Officer': 'shield-halved',
  'Medical Officer': 'shield-halved',
  'Civil Protection Officer (Science)': 'shield-halved',
  'Civil Protection Officer': 'shield-halved',
  'Union Miner': 'digging',
  'Union Engineer': 'gears',
  'Syndicate Operative': 'dragon',
  'Veteran Security Advisor': 'ribbon',
  'Pun Pun': 'paw',
  Overseer: 'handcuffs',
} as const;
