#define SOCIOSTABILITY_GREAT 1000
#define SOCIOSTABILITY_GOOD 900
#define SOCIOSTABILITY_OKAY 600
#define SOCIOSTABILITY_POOR 400
#define SOCIOSTABILITY_BAD 200
#define SOCIOSTABILITY_TERRIBLE 0

#define SOCIOSTABILITY_PASSIVE_GAIN -2 //by default -2, so -0.2% sociostability every 3 minutes.
